env:
  matrix:
  - NAME=test01
  - NAME=test02
  - NAME=test03
  - NAME=test04
  - NAME=test05
  - NAME=test06
  - NAME=test07
  - NAME=test08
  - NAME=test09
  - NAME=test10
services: docker
dist: bionic
language: python
before_install:
- openssl aes-256-cbc -K $encrypted_dcdd31726fd6_key -iv $encrypted_dcdd31726fd6_iv -in store.tar.enc -out store.tar -d
- tar xvf store.tar
install: docker build -t motutest -f Dockerfile .
script: docker run -a stdout -t motutest /home/motutest/test.sh 

